use crate::event::KeyCode as QuadKeyCode;
use android_activity::input::Keycode;

/// Translates `NDK` keycodes to miniquad's
pub fn translate_keycode_ndk(keycode: Keycode) -> QuadKeyCode {
	// TODO: I have no idea what key `QuadKeyCode::Left` and others really reference. If it's a bug - open a PR
	match keycode {
		Keycode::DpadLeft => QuadKeyCode::Left,
		Keycode::DpadRight => QuadKeyCode::Right,
		Keycode::DpadUp => QuadKeyCode::Up,
		Keycode::DpadDown => QuadKeyCode::Down,
		Keycode::Home => QuadKeyCode::Home,
		Keycode::Keycode0 => QuadKeyCode::Key0,
		Keycode::Keycode1 => QuadKeyCode::Key1,
		Keycode::Keycode2 => QuadKeyCode::Key2,
		Keycode::Keycode3 => QuadKeyCode::Key3,
		Keycode::Keycode4 => QuadKeyCode::Key4,
		Keycode::Keycode5 => QuadKeyCode::Key5,
		Keycode::Keycode6 => QuadKeyCode::Key6,
		Keycode::Keycode7 => QuadKeyCode::Key7,
		Keycode::Keycode8 => QuadKeyCode::Key8,
		Keycode::Keycode9 => QuadKeyCode::Key9,
		Keycode::Enter => QuadKeyCode::Enter,
		Keycode::A => QuadKeyCode::A,
		Keycode::B => QuadKeyCode::B,
		Keycode::C => QuadKeyCode::C,
		Keycode::D => QuadKeyCode::D,
		Keycode::E => QuadKeyCode::E,
		Keycode::F => QuadKeyCode::F,
		Keycode::G => QuadKeyCode::G,
		Keycode::H => QuadKeyCode::H,
		Keycode::I => QuadKeyCode::I,
		Keycode::J => QuadKeyCode::J,
		Keycode::K => QuadKeyCode::K,
		Keycode::L => QuadKeyCode::L,
		Keycode::M => QuadKeyCode::M,
		Keycode::N => QuadKeyCode::N,
		Keycode::O => QuadKeyCode::O,
		Keycode::P => QuadKeyCode::P,
		Keycode::Q => QuadKeyCode::Q,
		Keycode::R => QuadKeyCode::R,
		Keycode::S => QuadKeyCode::S,
		Keycode::T => QuadKeyCode::T,
		Keycode::U => QuadKeyCode::U,
		Keycode::V => QuadKeyCode::V,
		Keycode::W => QuadKeyCode::W,
		Keycode::X => QuadKeyCode::X,
		Keycode::Y => QuadKeyCode::Y,
		Keycode::Z => QuadKeyCode::Z,
		Keycode::Comma => QuadKeyCode::Comma,
		Keycode::Period => QuadKeyCode::Period,
		Keycode::AltLeft => QuadKeyCode::LeftAlt,
		Keycode::AltRight => QuadKeyCode::RightAlt,
		Keycode::ShiftLeft => QuadKeyCode::LeftShift,
		Keycode::ShiftRight => QuadKeyCode::RightShift,
		Keycode::Tab => QuadKeyCode::Tab,
		Keycode::Space => QuadKeyCode::Space,
		// android calls it Delete, but it has an icon of the Backspace and
		// expected behavior of the Backspace
		Keycode::Back => QuadKeyCode::Backspace,
		_ => QuadKeyCode::Unknown,
	}
}
